# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Development Push

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build
      env:
        NODE_ENV: production
        HOST: devflashcards.com
        DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
        DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
        DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        URL: https://api.dev.devflashcards.com/
    - name: 'Create artifact directory'
      run: mkdir artifact
    - name: 'Tar files'
      run: tar --exclude=node_modules --exclude=.git --exclude=.github -cvf ./artifact/devflashcards.tar ./
    - name: Upload via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: devflashcards.atthost24.pl
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./artifact/
        server-dir: ./artifact/
        log-level: verbose
        exclude: .git*
          - .git*/**
          - **/.git*/**
          - node_modules/**
          - node_modules/**/*
          - .env
    
